@startuml

title Диаграмма контекста Теплый дом

!RELATIVE_INCLUDE ?= "relative/absolute"
!include ./includes/C4_Context.puml

Person(user, "Пользователь", "Пользователь системы Тёплый дом")
Person(heatDevice, "Устройство отопления", "Устройство отопления, подключенное к системе Тёплый дом")
Person(sensor, "Датчик", "Датчик, подключенный к системе Тёплый дом")
Person(link, "Специалист по подключению", "Специалист по подключению к системе Тёплый дом")
Person(tech, "Технический специалист", "Специалист технической поддержки")

System(WarmHouseSystem, "Тёплый дом", "Система управляет устройствами отопления и датчиками")

Rel(user, WarmHouseSystem, "Работает с системой (смотрит температуру, включает/выключает отопление)")
Rel(WarmHouseSystem, sensor, "Запрашивает показания с датчика")
Rel(WarmHouseSystem, heatDevice, "Включает/выключает отопление")
Rel(link, WarmHouseSystem, "Регистрирует новые устройства")
Rel(tech, WarmHouseSystem, "Администрирует систему (по запросу пользователя и в целом)")


@enduml