@startuml C4_Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Контекстная диаграмма системы "Тёплый дом" (As-Is)

Person(homeowner, "Владелец дома", "Пользователь системы")
Person(technician, "Специалист по подключению", "Устанавливает и настраивает систему")

System(smarthome, "Система Тёплый дом", "Монолитное приложение для управления отоплением и мониторинга температуры")

System_Ext(heatingsystem, "Система отопления", "Физическое устройство управления отоплением")
System_Ext(temperaturesensor, "Датчик температуры", "Измеряет текущую температуру в доме")

Rel(homeowner, smarthome, "Использует веб-интерфейс для управления отоплением и просмотра температуры")
Rel(technician, smarthome, "Устанавливает и настраивает")
Rel(technician, heatingsystem, "Устанавливает и подключает")
Rel(technician, temperaturesensor, "Устанавливает и подключает")

Rel(smarthome, heatingsystem, "Отправляет команды (включить/выключить, установить температуру)")
Rel(smarthome, temperaturesensor, "Получает данные о температуре")

@enduml 